<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

namespace Pbdb\db_task;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pbdb.db_task.data_schedule</code>
 */
class data_schedule extends \Google\Protobuf\Internal\Message
{
    /**
     *EFinshTask
     *
     * Generated from protobuf field <code>optional int32 m_type = 1;</code>
     */
    protected $m_type = null;
    /**
     * Generated from protobuf field <code>repeated int32 m_parmint = 2;</code>
     */
    private $m_parmint;
    /**
     * Generated from protobuf field <code>repeated int32 m_sumint = 3;</code>
     */
    private $m_sumint;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $m_type
     *          EFinshTask
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $m_parmint
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $m_sumint
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Db::initOnce();
        parent::__construct($data);
    }

    /**
     *EFinshTask
     *
     * Generated from protobuf field <code>optional int32 m_type = 1;</code>
     * @return int
     */
    public function getMType()
    {
        return isset($this->m_type) ? $this->m_type : 0;
    }

    public function hasMType()
    {
        return isset($this->m_type);
    }

    public function clearMType()
    {
        unset($this->m_type);
    }

    /**
     *EFinshTask
     *
     * Generated from protobuf field <code>optional int32 m_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMType($var)
    {
        GPBUtil::checkInt32($var);
        $this->m_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 m_parmint = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMParmint()
    {
        return $this->m_parmint;
    }

    /**
     * Generated from protobuf field <code>repeated int32 m_parmint = 2;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMParmint($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->m_parmint = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 m_sumint = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMSumint()
    {
        return $this->m_sumint;
    }

    /**
     * Generated from protobuf field <code>repeated int32 m_sumint = 3;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMSumint($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->m_sumint = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(data_schedule::class, \Pbdb\db_task_data_schedule::class);

