<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

namespace Pbdb\db_task;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pbdb.db_task.data</code>
 */
class data extends \Google\Protobuf\Internal\Message
{
    /**
     * 任务id
     *
     * Generated from protobuf field <code>optional int32 m_taskid = 1;</code>
     */
    protected $m_taskid = null;
    /**
     * 接收任务时间
     *
     * Generated from protobuf field <code>optional int32 m_receiveutc = 2;</code>
     */
    protected $m_receiveutc = null;
    /**
     * 完成任务时间
     *
     * Generated from protobuf field <code>optional int32 m_finshutc = 3;</code>
     */
    protected $m_finshutc = null;
    /**
     * Generated from protobuf field <code>optional int32 m_parmint1 = 4;</code>
     */
    protected $m_parmint1 = null;
    /**
     * Generated from protobuf field <code>optional int32 m_parmint2 = 5;</code>
     */
    protected $m_parmint2 = null;
    /**
     * Generated from protobuf field <code>optional string m_parmstring1 = 6;</code>
     */
    protected $m_parmstring1 = null;
    /**
     * Generated from protobuf field <code>optional string m_parmstring2 = 7;</code>
     */
    protected $m_parmstring2 = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $m_taskid
     *           任务id
     *     @type int $m_receiveutc
     *           接收任务时间
     *     @type int $m_finshutc
     *           完成任务时间
     *     @type int $m_parmint1
     *     @type int $m_parmint2
     *     @type string $m_parmstring1
     *     @type string $m_parmstring2
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Db::initOnce();
        parent::__construct($data);
    }

    /**
     * 任务id
     *
     * Generated from protobuf field <code>optional int32 m_taskid = 1;</code>
     * @return int
     */
    public function getMTaskid()
    {
        return isset($this->m_taskid) ? $this->m_taskid : 0;
    }

    public function hasMTaskid()
    {
        return isset($this->m_taskid);
    }

    public function clearMTaskid()
    {
        unset($this->m_taskid);
    }

    /**
     * 任务id
     *
     * Generated from protobuf field <code>optional int32 m_taskid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMTaskid($var)
    {
        GPBUtil::checkInt32($var);
        $this->m_taskid = $var;

        return $this;
    }

    /**
     * 接收任务时间
     *
     * Generated from protobuf field <code>optional int32 m_receiveutc = 2;</code>
     * @return int
     */
    public function getMReceiveutc()
    {
        return isset($this->m_receiveutc) ? $this->m_receiveutc : 0;
    }

    public function hasMReceiveutc()
    {
        return isset($this->m_receiveutc);
    }

    public function clearMReceiveutc()
    {
        unset($this->m_receiveutc);
    }

    /**
     * 接收任务时间
     *
     * Generated from protobuf field <code>optional int32 m_receiveutc = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMReceiveutc($var)
    {
        GPBUtil::checkInt32($var);
        $this->m_receiveutc = $var;

        return $this;
    }

    /**
     * 完成任务时间
     *
     * Generated from protobuf field <code>optional int32 m_finshutc = 3;</code>
     * @return int
     */
    public function getMFinshutc()
    {
        return isset($this->m_finshutc) ? $this->m_finshutc : 0;
    }

    public function hasMFinshutc()
    {
        return isset($this->m_finshutc);
    }

    public function clearMFinshutc()
    {
        unset($this->m_finshutc);
    }

    /**
     * 完成任务时间
     *
     * Generated from protobuf field <code>optional int32 m_finshutc = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMFinshutc($var)
    {
        GPBUtil::checkInt32($var);
        $this->m_finshutc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 m_parmint1 = 4;</code>
     * @return int
     */
    public function getMParmint1()
    {
        return isset($this->m_parmint1) ? $this->m_parmint1 : 0;
    }

    public function hasMParmint1()
    {
        return isset($this->m_parmint1);
    }

    public function clearMParmint1()
    {
        unset($this->m_parmint1);
    }

    /**
     * Generated from protobuf field <code>optional int32 m_parmint1 = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMParmint1($var)
    {
        GPBUtil::checkInt32($var);
        $this->m_parmint1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 m_parmint2 = 5;</code>
     * @return int
     */
    public function getMParmint2()
    {
        return isset($this->m_parmint2) ? $this->m_parmint2 : 0;
    }

    public function hasMParmint2()
    {
        return isset($this->m_parmint2);
    }

    public function clearMParmint2()
    {
        unset($this->m_parmint2);
    }

    /**
     * Generated from protobuf field <code>optional int32 m_parmint2 = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMParmint2($var)
    {
        GPBUtil::checkInt32($var);
        $this->m_parmint2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string m_parmstring1 = 6;</code>
     * @return string
     */
    public function getMParmstring1()
    {
        return isset($this->m_parmstring1) ? $this->m_parmstring1 : '';
    }

    public function hasMParmstring1()
    {
        return isset($this->m_parmstring1);
    }

    public function clearMParmstring1()
    {
        unset($this->m_parmstring1);
    }

    /**
     * Generated from protobuf field <code>optional string m_parmstring1 = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMParmstring1($var)
    {
        GPBUtil::checkString($var, True);
        $this->m_parmstring1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string m_parmstring2 = 7;</code>
     * @return string
     */
    public function getMParmstring2()
    {
        return isset($this->m_parmstring2) ? $this->m_parmstring2 : '';
    }

    public function hasMParmstring2()
    {
        return isset($this->m_parmstring2);
    }

    public function clearMParmstring2()
    {
        unset($this->m_parmstring2);
    }

    /**
     * Generated from protobuf field <code>optional string m_parmstring2 = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setMParmstring2($var)
    {
        GPBUtil::checkString($var, True);
        $this->m_parmstring2 = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(data::class, \Pbdb\db_task_data::class);

