<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gm.proto

namespace GM;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * [回复]获取公告
 *
 * Generated from protobuf message <code>GM.PROBUFF_GM_GET_NOTICE_RESPONSE</code>
 */
class PROBUFF_GM_GET_NOTICE_RESPONSE extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .GM.gm_notice m_notice = 3;</code>
     */
    private $m_notice;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\GM\gm_notice>|\Google\Protobuf\Internal\RepeatedField $m_notice
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .GM.gm_notice m_notice = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMNotice()
    {
        return $this->m_notice;
    }

    /**
     * Generated from protobuf field <code>repeated .GM.gm_notice m_notice = 3;</code>
     * @param array<\GM\gm_notice>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMNotice($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GM\gm_notice::class);
        $this->m_notice = $arr;

        return $this;
    }

}

