#pragma once

namespace ngl
{
	enum NET_CONFIG
	{
		NET_CONFIG_SEND_BUFF_MAXBYTE = 8129,
		NET_CONFIG_RECV_BUFF_MAXBYTE = 8129,
		NET_CONFIG_LOGIC_PTHREAD_MAX_SIZE = 8,
		NET_CONFIG_SOCKET_PTHREAD_MAX_SIZE = 8,
	};

}//namespace ngl