<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

namespace Pbdb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *ENUM_DB_GUILD,			// 工会数据
 *
 * Generated from protobuf message <code>pbdb.db_guild</code>
 */
class db_guild extends \Google\Protobuf\Internal\Message
{
    /**
     * 工会id
     *
     * Generated from protobuf field <code>optional int64 m_id = 1;</code>
     */
    protected $m_id = null;
    /**
     * 工会名称
     *
     * Generated from protobuf field <code>optional string m_guild = 2;</code>
     */
    protected $m_guild = null;
    /**
     * 工会会长
     *
     * Generated from protobuf field <code>optional int64 m_leader = 3;</code>
     */
    protected $m_leader = null;
    /**
     * 工会成员
     *
     * Generated from protobuf field <code>repeated int64 m_members = 4;</code>
     */
    private $m_members;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $m_id
     *           工会id
     *     @type string $m_guild
     *           工会名称
     *     @type int|string $m_leader
     *           工会会长
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $m_members
     *           工会成员
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Db::initOnce();
        parent::__construct($data);
    }

    /**
     * 工会id
     *
     * Generated from protobuf field <code>optional int64 m_id = 1;</code>
     * @return int|string
     */
    public function getMId()
    {
        return isset($this->m_id) ? $this->m_id : 0;
    }

    public function hasMId()
    {
        return isset($this->m_id);
    }

    public function clearMId()
    {
        unset($this->m_id);
    }

    /**
     * 工会id
     *
     * Generated from protobuf field <code>optional int64 m_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMId($var)
    {
        GPBUtil::checkInt64($var);
        $this->m_id = $var;

        return $this;
    }

    /**
     * 工会名称
     *
     * Generated from protobuf field <code>optional string m_guild = 2;</code>
     * @return string
     */
    public function getMGuild()
    {
        return isset($this->m_guild) ? $this->m_guild : '';
    }

    public function hasMGuild()
    {
        return isset($this->m_guild);
    }

    public function clearMGuild()
    {
        unset($this->m_guild);
    }

    /**
     * 工会名称
     *
     * Generated from protobuf field <code>optional string m_guild = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMGuild($var)
    {
        GPBUtil::checkString($var, True);
        $this->m_guild = $var;

        return $this;
    }

    /**
     * 工会会长
     *
     * Generated from protobuf field <code>optional int64 m_leader = 3;</code>
     * @return int|string
     */
    public function getMLeader()
    {
        return isset($this->m_leader) ? $this->m_leader : 0;
    }

    public function hasMLeader()
    {
        return isset($this->m_leader);
    }

    public function clearMLeader()
    {
        unset($this->m_leader);
    }

    /**
     * 工会会长
     *
     * Generated from protobuf field <code>optional int64 m_leader = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMLeader($var)
    {
        GPBUtil::checkInt64($var);
        $this->m_leader = $var;

        return $this;
    }

    /**
     * 工会成员
     *
     * Generated from protobuf field <code>repeated int64 m_members = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMMembers()
    {
        return $this->m_members;
    }

    /**
     * 工会成员
     *
     * Generated from protobuf field <code>repeated int64 m_members = 4;</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMMembers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->m_members = $arr;

        return $this;
    }

}

