<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

namespace Pbdb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *ENUM_DB_BAG,			// 背包数据
 *
 * Generated from protobuf message <code>pbdb.item</code>
 */
class item extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int32 m_id = 1;</code>
     */
    protected $m_id = null;
    /**
     * tab id
     *
     * Generated from protobuf field <code>optional int32 m_tid = 2;</code>
     */
    protected $m_tid = null;
    /**
     * Generated from protobuf field <code>optional int32 m_count = 3;</code>
     */
    protected $m_count = null;
    /**
     * ## 卡牌 装备
     *
     * Generated from protobuf field <code>optional int32 m_lv = 4;</code>
     */
    protected $m_lv = null;
    /**
     * 星级
     *
     * Generated from protobuf field <code>optional int32 m_star = 5;</code>
     */
    protected $m_star = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $m_id
     *     @type int $m_tid
     *           tab id
     *     @type int $m_count
     *     @type int $m_lv
     *           ## 卡牌 装备
     *     @type int $m_star
     *           星级
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Db::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int32 m_id = 1;</code>
     * @return int
     */
    public function getMId()
    {
        return isset($this->m_id) ? $this->m_id : 0;
    }

    public function hasMId()
    {
        return isset($this->m_id);
    }

    public function clearMId()
    {
        unset($this->m_id);
    }

    /**
     * Generated from protobuf field <code>optional int32 m_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMId($var)
    {
        GPBUtil::checkInt32($var);
        $this->m_id = $var;

        return $this;
    }

    /**
     * tab id
     *
     * Generated from protobuf field <code>optional int32 m_tid = 2;</code>
     * @return int
     */
    public function getMTid()
    {
        return isset($this->m_tid) ? $this->m_tid : 0;
    }

    public function hasMTid()
    {
        return isset($this->m_tid);
    }

    public function clearMTid()
    {
        unset($this->m_tid);
    }

    /**
     * tab id
     *
     * Generated from protobuf field <code>optional int32 m_tid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMTid($var)
    {
        GPBUtil::checkInt32($var);
        $this->m_tid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 m_count = 3;</code>
     * @return int
     */
    public function getMCount()
    {
        return isset($this->m_count) ? $this->m_count : 0;
    }

    public function hasMCount()
    {
        return isset($this->m_count);
    }

    public function clearMCount()
    {
        unset($this->m_count);
    }

    /**
     * Generated from protobuf field <code>optional int32 m_count = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->m_count = $var;

        return $this;
    }

    /**
     * ## 卡牌 装备
     *
     * Generated from protobuf field <code>optional int32 m_lv = 4;</code>
     * @return int
     */
    public function getMLv()
    {
        return isset($this->m_lv) ? $this->m_lv : 0;
    }

    public function hasMLv()
    {
        return isset($this->m_lv);
    }

    public function clearMLv()
    {
        unset($this->m_lv);
    }

    /**
     * ## 卡牌 装备
     *
     * Generated from protobuf field <code>optional int32 m_lv = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMLv($var)
    {
        GPBUtil::checkInt32($var);
        $this->m_lv = $var;

        return $this;
    }

    /**
     * 星级
     *
     * Generated from protobuf field <code>optional int32 m_star = 5;</code>
     * @return int
     */
    public function getMStar()
    {
        return isset($this->m_star) ? $this->m_star : 0;
    }

    public function hasMStar()
    {
        return isset($this->m_star);
    }

    public function clearMStar()
    {
        unset($this->m_star);
    }

    /**
     * 星级
     *
     * Generated from protobuf field <code>optional int32 m_star = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMStar($var)
    {
        GPBUtil::checkInt32($var);
        $this->m_star = $var;

        return $this;
    }

}

