name: Clang Format Check
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Clang-Format
        run: sudo apt install clang-format -y

      - name: Check code style
        run: |
          find ./public/cpp \( -path "*/third_party" -o -path "*/pb" \) -prune -o \( -name "*.h" -o -name "*.hpp" -o -name "*.cpp" \) -type f -print0 \
            | xargs -0 clang-format --dry-run --Werror
